# Change 'comments' to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'apham'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-91332049-1'

menu:
  - name: 主页
    link: /
  - name: 推荐文章
    submenu:
      - name: CICD
        link: /tags/#cicd
      - name: KUBERNETES
        link: /tags/#kubernetes
  - name: 专题
    submenu:
      - name: 调用链追踪
        link: /tags/#tracing
      - name: Envoy
        link: /tags/#envoy
  - name: 分类
    submenu:
      - name: 网络知识
        link: /tags/#network
      - name: 操作系统
        link: /tags/#os
      - name: CICD
        link: /tags/#cicd
      - name: Kubernetes
        link: /tags/#kubernetes
      - name: ServiceMesh
        link: /tags/#srvicemesh
      - name: 监控
        link: /tags/#monitor
      - name: 开发技术
        link: /tags/#develop
      - name: 数据库
        link: /tags/#database
      - name: 系统架构
        link: /tags/#architecture
      - name: 企业IT
        link: /tags/#it
  - name: 标签
    link: /tags

  - name: 目录
    link: /categories

  - name: 关于
    link: /about
  - name: 联系
    submenu:
      - name: GitHub
        icon: github
        link: https://github.com/FinTechOps
#      - name: LinkedIn
#        icon: linkedin-square
#        link: http://www.linkedin.com/in/alainpham
#      - name: Twitter
#        icon: twitter
#        link: https://twitter.com/koint
    
